---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-task
spec:
  steps:
    - name: echo
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        echo "Good Morning!"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: check-status
spec:
  tasks:
    - name: hello-task
      taskRef:
        name: hello-task
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: hello-pipeline-template
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pipelinerun-with-taskspec-
      spec:
        pipelineRef:
          name: check-status
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: manual-hello-pipeline-binding
spec:
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: manual-hello-listener
spec:
  triggers:
    - binding:
        name: manual-hello-pipeline-binding
      template:
        name: hello-pipeline-template
