apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: missing-pipeline-template
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: staging-pr-
      spec:
        pipelineRef:
            name: staging-status-check
        serviceAccount: 'default'
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: manual-missing-pipeline-binding
spec:
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: manual-missing-pipeline-listener
spec:
  triggers:
    - binding:
        name: manual-missing-pipeline-binding
      template:
        name: missing-pipeline-template
